version: '3.9'

volumes:
  neo4j_data:
  redis_data:

services:

  &redis-service redis:
    image: redis:alpine
    restart: always
    ports:
      - "${REDIS_PORT:-6379}:6379"
    volumes:
      - redis_data:/data:delegated
    sysctls:
      net.core.somaxconn: "65535"
    ulimits:
      nproc: 65536
      nofile:
        soft: 65536
        hard: 65536

  ### Redis Manager #################################################

  redis-ui:
    image: erikdubbelboer/phpredisadmin:latest
    environment:
      # - ADMIN_USER=admin
      # - ADMIN_PASS=admin
      REDIS_1_HOST: *redis-service
      REDIS_1_PORT: 6379
    ports:
      - "${REDIS_UI_PORT:-8081}:80"
    depends_on:
      - *redis-service

  neo4j:
    image: neo4j:latest
    restart: always
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - neo4j_data:/data
    environment:
      - NEO4J_AUTH=neo4j/frYigdzlBLnmVNMmkbcKZg11Dc1h_vptRDsLJwr3Umc
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
      # Raise memory limits
      - NEO4J_server.memory.pagecache.size=1G
      - NEO4J_server.memory.heap.initial_size=1G
      - NEO4J_server_memory_heap_max__size=1G
      - NEO4JLABS_PLUGINS=["apoc"]

  #  kafka-ui:
  #    image: provectuslabs/kafka-ui
  #    container_name: kafka-ui
  #    ports:
  #      - "8080:8080"
  #    restart: always
  #    environment:
  #      - KAFKA_CLUSTERS_0_NAME=local
  #      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:9092
  #      - KAFKA_CLUSTERS_0_ZOOKEEPER=kafka:2181

  kafka:
    image: bitnami/kafka:3.3
    ports:
      - '9092:9092'
    restart: always
    environment:
      ALLOW_PLAINTEXT_LISTENER: yes
      KAFKA_BROKER_ID: 1
      KAFKA_ENABLE_KRAFT: yes
      KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE: yes
      KAFKA_CFG_PROCESS_ROLES: broker,controller
      KAFKA_CFG_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_CFG_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CFG_LISTENERS: INTERNAL://kafka:29092,EXTERNAL://kafka:9092,CONTROLLER://:9093
      KAFKA_CFG_ADVERTISED_LISTENERS: INTERNAL://kafka:29092,EXTERNAL://localhost:9092
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093

  # Kafka UI
  # See: https://hub.docker.com/r/rsmnarts/kowl
  kafka-ui:
    image: rsmnarts/kowl:latest
    environment:
      KAFKA_BROKERS: 'kafka:29092'
    restart: 'on-failure'
    ports:
      - '${KAFKA_UI_PORT:-9000}:8080'
    depends_on:
      - kafka
