name: Publish Collector

on:
  push:
    branches: [ main ]
    paths:
      - apps/collector/src/**
  workflow_dispatch:

env:
  APP_NAME: collector
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:

  build:
    runs-on: ubuntu-latest
    name: Build and Push Docker Image
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-buildx-action@v2
      - uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Bump version
        id: version
        uses: phips28/gh-action-bump-version@master
        with:
          skip-tag: 'true'
          tag-prefix: 'v'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PACKAGEJSON_DIR: apps/${{ env.APP_NAME }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: ./
          file: ./apps/${{ env.APP_NAME }}/Dockerfile
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ github.repository }}_${{ env.APP_NAME }}:${{ steps.version.outputs.newTag }}
            ${{ env.REGISTRY }}/${{ github.repository }}_${{ env.APP_NAME }}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
